language: python
python:
  - "2.6"
  - "2.7"
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
script: cd ./testproject; python manage.py test phonenumber_field testapp